component_depth: 5
languages:
- java

exclude:
- /README_rsc/*
- /README.md
- /Monopoly/1.txt
- /Monopoly/android/*
- /Monopoly/build/*
- /Monopoly/build.gradle
- /Monopoly/desktop/*
- /Monopoly/gradle/*
- /Monopoly/gradle.properties
- /Monopoly/gradlew/*
- /Monopoly/gradlew.bat
- /Monopoly/html/*
- /Monopoly/ios/*
- /Monopoly/local.properties
- /Monopoly/Monopoly.iml
- /Monopoly/settings.gradle
- /Monopoly/core/src/com/*
- /Monopoly/core/src/scenes/*
- /Monopoly/core/src/screens/*